### ISSUE TITLE
vbs script is not working

### ISSUE THREAD

**Issue by Scifire** [PluginsOCSInventory-NG/teamviewer#1]
Hello,
we use Server OCS 2.3 on Ubuntu 16.04, Agent 2.3.0.0. on Win 10, Teamviewer 9
Installing the plugin was fine but the vbs won´t work on my win10.
![grafik](https://cloud.githubusercontent.com/assets/17220258/21712708/8b92267c-d3f6-11e6-9929-24ae98781e85.png)
(Error: Reg Key can´t open to read)

i´ve checked my reg and noticed that the path is not vaild which the script call. 
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\TeamViewer\Version9\ClientID
is the path for the client id on my machine.

**Comment by gillesdubois** [comment]
Hi,

Thx for your report.
This plugin is recent so we didn't covered all version / installations.

We will be updating the vbs soon :)

**Comment by steph78630** [comment]
Hi @scifire91 and @gillesdubois,

I just updated the VBS script for you on GitHub... waiting for validation.

**Comment by vdeville** [comment]
Helllo @scifire91 can you re-test with new version ?

Thanks

**Comment by Scifire** [comment]
@MyTheValentinus @steph78630 
i replaced the vb script with the new one (should i do anything else?) 
Script is working but i didn´t get any information from it as you can see in screenshot.
![image](https://user-images.githubusercontent.com/17220258/28564943-ef925b34-712a-11e7-95c2-f6d127d2ddec.png)

**Comment by vdeville** [comment]
What is your teamviewer version ? And your system architecture?

**Comment by Scifire** [comment]
Teamviewer Version 9.0.41110
System: Win 10 Pro 64 Bit

**Comment by vdeville** [comment]
Ho ! Ok i test on 11 and 12. Not 9 version. It's very old version of Teamviewer.

**Comment by Scifire** [comment]
We´re using a paid enterprise version, you won´t upgrade every year for not really new functions ^^
If it´s not working with 9 not a big deal, but maybe document it that no one other opens an issue for that.

**Comment by vdeville** [comment]
I begin test on this version and come back here soon !

**Comment by vkapas** [comment]
Same problem on 50% PCs in network.
OCS 2.3.1, Ubuntu 16.04, Agent 2.3, Windows 7 SP1, TeamViewer Host 11 and 12.

OCSInventory.log:
```
	EXECUTABLE PLUGIN => Searching for VBS script(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	EXECUTABLE PLUGIN => Found executable plugin <teamviewer.vbs>
	WARNING *** EXECUTABLE PLUGIN => Executable plugin <C:\Program Files\OCS Inventory Agent\plugins\teamviewer.vbs> output is not UTF-8 encoded or an XML document, trying to UTF-8 encode
	WARNING *** EXECUTABLE PLUGIN => Executable plugin <C:\Program Files\OCS Inventory Agent\plugins\teamviewer.vbs> output encoded to UTF-8, trying to reload XML document
ERROR *** EXECUTABLE PLUGIN => Executable plugin <C:\Program Files\OCS Inventory Agent\plugins\teamviewer.vbs> output is not a valid XML document
	EXECUTABLE PLUGIN => Searching for executable(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
```

**Comment by Scifire** [comment]
OCS 2.3 is already outdated so i close this.
