### ISSUE TITLE
Agent don't load teamviewer plugin

### ISSUE THREAD

**Issue by gally11** [PluginsOCSInventory-NG/teamviewer#6]
Hello,

My config
OCS Server on debian v 2.3.1
teamviewer plugin v1.1 installed with success on server

I copied teamviewer.vbs in C:\Program Files (x86)\OCS Inventory Agent\Plugins

When I forced the inventory, in log, under load plug-in, nothing appears:

> Starting OCS Inventory NG Agent on Friday, November 23, 2018 11:23:28.
> AGENT => Running OCS Inventory NG Agent Version 2.3.1.1
>AGENT => Using OCS Inventory NG FrameWork Version 2.3.1.1
>AGENT => Loading plug-in(s)
>AGENT => Using network connection with Communication Server
>AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.1.1>
>AGENT => Sending Prolog
>AGENT => Prolog successfully sent
>AGENT => Inventory required
>AGENT => Launching hardware and software checks
>AGENT => Sending Inventory
>INVENTORY => Inventory changed since last run
>AGENT => Inventory successfully sent
>AGENT =>  Communication Server ask for Package Download
>AGENT => Unloading communication provider
>AGENT => Unloading plug-in(s)
>AGENT => Execution duration: 00:01:02.`

And in server the inventory had the good time of update but nothing in teamviewer section.

When I double click on VBS, a little windows opened wtih teamviewers info.

I tested on a second computer, same problem, I don't understand.

Thks a lot.

**Comment by Draktann** [comment]
Hi,

Can you change your debug mode to "Debug=2" in ocsinventory.ini and push again your log ?

**Comment by gally11** [comment]
Sorry, I forgot the ticket.

I had install newier version of OCS Server and it's good.
