### ISSUE TITLE
Pack it in a folder

### ISSUE THREAD

**Issue by Spanni26** [PluginsOCSInventory-NG/teamviewer#8]
According to https://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/#using-extension-engine the plugin must be unzipped at the extensions directory. But then, there are several files an directories laying around, but the have to be in a folder "Teamviewer" for installation.
So, create a folder and zip it, please :)

**Comment by fbomj** [comment]
Fixed
