### ISSUE TITLE
OCS Server shows only "Processing"

### ISSUE THREAD

**Issue by Spanni26** [PluginsOCSInventory-NG/teamviewer#9]
The ocs Server gui only shows "Processing..."  at the teamviewer part when looking at the "Miscellaneous"  menu of a machine.

OCS Server 2.6 on opensuse Tumbleweed, latest Teamviewer plugin release.

**Comment by nini57** [comment]
Hi, I've the same problem

**Comment by fbomj** [comment]
Update to latest version
